### ISSUE TITLE
Generate an instruction trace using champSim

### ISSUE THREAD

**Issue by FuLiuwei** [ChampSim/ChampSim#474] opened 2024-06-03 11:55 UTC
Hi, I have encountered an issue and I need everyone's help: How can I fix a seed and generate an instruction trace using champSim? I have downloaded the spec06 and spec17 traces, but I am unsure how to convert it into an instruction trace (Address, pc).

**Comment by ngober** [comment] 2024-06-03 15:07
Duplicate of #475

**Closed by ngober** 2024-06-03 15:07 UTC
Labels: feature request
