### ISSUE TITLE
4-core deadlock and LQ/SQ assert

### ISSUE THREAD

**Issue by cmolder** [ChampSim/ChampSim#294] opened 2022-11-17 20:18 UTC
**Describe the bug**
I've discovered a couple of deadlock/assertion scenarios on SPEC '06 and CloudSuite, using a 4-core configuration of ChampSim. A partner and I think these bugs may be related.

**Bug 1: milc deadlock**
When running 4 instances of milc (SPEC 06) on a 4-core system, [we see a deadlock](https://utexas.box.com/s/sk0m7syrsdv3gvzdz8xeuq08a56pf6m5) around instruction 92,000,000 (using master branch).

***To Reproduce***
1. Download the trace ([milc_744B](https://utexas.box.com/s/62h6mynx9luyzsbrlwne33imiwps5c9r))
2. Build ChampSim on the [this config](https://utexas.box.com/s/ry0gso3k03fvecmk742n1611ripwwl8w)
3. Run ChampSim:
```
./bin/champsim_triage_4core --warmup_instructions 200000000 --simulation_instructions 50000000 milc_744B.trace.gz milc_744B.trace.gz milc_744B.trace.gz milc_744B.trace.gz
```
4. See deadlock around instruction 92,000,000.

**Bug 2: streaming LQ/SQ assertion fail**
When running the 4-core streaming (CloudSuite) benchmark on a 4-core system, [we see the following error](https://utexas.box.com/s/dwdl0ecs10vfco5q00awpe29o4ovcgj7) around instruction 14,000,000 (using master branch).
```
src/ooo_cpu.cc:856: void O3_CPU::execute_store(std::vector<LSQ_ENTRY>::iterator): Assertion `dependent->lq_index[j]->producer_id == sq_it->instr_id' failed.
```

**Edit**: I checked this on single-core, and we get the same error. Specifically, the following IDs trip the assert:
- `dependent->lq_index[j]->producer_id` = -1
- `j` = 0
- `sq_it->instr_id` = 12252552

***To Reproduce***
1. Download the traces (streaming_phase0): (**TODO**: upload these traces)
2. Build ChampSim on [this config](https://utexas.box.com/s/ry0gso3k03fvecmk742n1611ripwwl8w)
3. Run ChampSim:
```
./bin/champsim_triage_4core --warmup_instructions 200000000 --simulation_instructions 50000000 streaming_phase0_core0.trace.xz streaming_phase0_core1.trace.xz streaming_phase0_core2.trace.xz streaming_phase0_core3.trace.xz
```
4. See assertion around instruction 14,000,000.

**Additional context**
I discovered this bug while using this config on my fork of ChampSim. On my fork, in which I've made some changes to prefetching and added some prefetcher callback functions, I've noticed another 4-core error message when running 4 instances of mcf.

Around instruction 30,000,000 (within 200M warmup):
```
src/cache.cc:450: virtual int CACHE::add_rq(PACKET*): Assertion `packet->address != 0' failed.
```

I haven't been able to confirm this one on the master branch of ChampSim, as it only happens when I run a custom prefetcher (which depends on changes I've made to the prefetcher/cache framework). With no prefetching or with other prefetchers, it completes.

These bugs may be related to #248 and #246, but I'm seeing it on the master branch.

Thanks for your help!

**Comment by ngober** [comment] 2023-02-24 18:32
I ran the configuration and traces you provided on the develop branch, and I can't reproduce the deadlock. Are you still seeing this? If not, I'll assume it's resolved and I'll close the issue.

**Closed** 2023-03-07 16:53 UTC
Labels: bug, Status: Cannot Reproduce
